import { BossTranslation } from '../types';

export const mechSpiderTranslations: BossTranslation = {
    ja: {},
    en: {
        displayName: 'Mech Spider',
        description: 'A general-purpose repair mech.',
        questNote: 'Survivors from ancient ruins report a strange spider within. To make the investigation safe, you are tasked with defeating it.',
        appearanceNote: 'Machine, spider, red sensor lights, synthetic threads, mechanical legs',
        victoryTrophy: {
            name: 'Synthetic Thread',
            description: 'Special synthetic thread generated by the Mech Spider, incredibly tough and packed with ancient tech.'
        },
        defeatTrophy: {
            name: 'Shrinking Fluid',
            description: 'A shrinking solution produced inside the Mech Spider that reduces anything it touches.'
        }
    }
};
