name: Auto Release on Tag Push

on:
  push:
    tags:
      # release/v で始まるタグのみにマッチ (例: release/v1.0.0, release/v0.1.0)
      - 'release/v*'

# GITHUB_TOKENの権限設定
permissions:
  contents: write  # リリース作成に必要

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 完全な履歴を取得してリリースノート生成を改善
        fetch-depth: 0
    
    - name: Extract version from tag
      id: extract-version
      run: |
        # タグ名から release/ プレフィックスを削除
        # 例: release/v1.0.0 → v1.0.0
        VERSION=${GITHUB_REF#refs/tags/release/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
    
    - name: Check if release already exists
      id: check-release
      run: |
        # 同じタグのリリースが既に存在するかチェック
        if gh release view "${{ steps.extract-version.outputs.version }}" > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Release ${{ steps.extract-version.outputs.version }} already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Release ${{ steps.extract-version.outputs.version }} does not exist"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create GitHub Release
      if: steps.check-release.outputs.exists == 'false'
      run: |
        gh release create "${{ steps.extract-version.outputs.version }}" \
          --title "Release ${{ steps.extract-version.outputs.version }}" \
          --generate-notes \
          --latest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Release creation completed
      if: steps.check-release.outputs.exists == 'false'
      run: |
        echo "✅ GitHub Release ${{ steps.extract-version.outputs.version }} has been created successfully!"
        echo "🚀 The deploy workflow will be triggered automatically."
    
    - name: Release already exists
      if: steps.check-release.outputs.exists == 'true'
      run: |
        echo "ℹ️ Release ${{ steps.extract-version.outputs.version }} already exists. Skipping creation."